# Generated by Django 5.2.3 on 2025-06-26 10:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_company_name_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_goals',
            field=models.TextField(blank=True, help_text="User's fitness goals"),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions to be aware of'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_class_types',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred class types'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio or instructor's description"),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Gym or company name for instructors', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('instructor', 'Gym Instructor'), ('admin', 'Admin')], default='user', max_length=12),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('weekly_workout_goal', models.PositiveIntegerField(default=3, help_text='Target workouts per week')),
                ('preferred_workout_duration', models.PositiveIntegerField(default=60, help_text='Preferred workout duration in minutes')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['experience_level'], name='user_profil_experie_b7596c_idx'), models.Index(fields=['profile_visibility'], name='user_profil_profile_5d5ee7_idx')],
            },
        ),
    ]
