# Generated by Django 5.2.3 on 2025-06-26 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('waitlisted', 'Waitlisted')], db_index=True, default='booked', max_length=12)),
                ('booking_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cancellation_time', models.DateTimeField(blank=True, null=True)),
                ('is_waitlisted', models.BooleanField(default=False)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements from the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_time'],
                'indexes': [models.Index(fields=['user'], name='bookings_user_id_fdc49e_idx'), models.Index(fields=['class_schedule'], name='bookings_class_s_e3ce91_idx'), models.Index(fields=['status'], name='bookings_status_51373b_idx'), models.Index(fields=['is_waitlisted'], name='bookings_is_wait_2c633f_idx')],
                'unique_together': {('user', 'class_schedule')},
            },
        ),
        migrations.CreateModel(
            name='ClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classes.class')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classes.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='class_revie_user_id_34c65b_idx'), models.Index(fields=['class_schedule'], name='class_revie_class_s_b68e63_idx'), models.Index(fields=['class_obj'], name='class_revie_class_o_5f6a48_idx'), models.Index(fields=['rating'], name='class_revie_rating_d8bf62_idx')],
                'unique_together': {('user', 'class_schedule')},
            },
        ),
    ]
